name: examplscreenshot
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  share_plus: ^4.0.10
  screenshot: ^1.2.3
  flutter_html: ^2.2.1
  image_picker: ^0.8.5+3
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  fluttertoast: ^8.0.9
  dio: ^4.0.6

  baseflow_plugin_template:
    git:
      url: https://github.com/Baseflow/baseflow_plugin_template.git
      ref: v2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
permission_handler:
    # When depending on this package from a real application you should use:
    #   permission_handler: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
  path: ../

  url_launcher: ^6.0.12

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

